version: '3'
services:
  mongo:
    image: mongo:4
    ports:
      - '27017:27017'
    # environment:
    #     - MONGO_INITDB_ROOT_USERNAME=mongo
    #     - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - ./mongo-data:/data/db
  postgres:
    command:
      - 'postgres'
      - '-c'
      - 'listen_addresses=*'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:14
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.5-alpine
    ports:
      - '6379:6379'
